### ISSUE TITLE
Provide options besides isomorphic-ws

### ISSUE THREAD

**Issue by Mehdi-Verfaillie** [tiagosiebler/okx-api#15]
Good morning,

When using `WebsocketClient`, it seems that, because of the implementation, we have no choice but to use `isomorphic-ws` which itself uses [websocket](https://github.com/websockets/ws).

Would it be possible to specify in `WSClientConfigurableOptions` an option to define a custom web server while keeping the original implementation of this library by default ?

Two reason behind this. The first is performances which lead to server cost. The second is to better respect Dependency Inversion Principle.

I'm interested in hearing your thoughts. 
Let's me know~

**Comment by tiagosiebler** [comment]
Hi @Mehdi-Verfaillie 

You've probably seen this already but just in case - the implementation behind `isomorphic-ws` is extremely simple, purely providing an alternative if my SDKs are being used in frontend environments, since the node `ws` package cannot be used in the browser. That means in a node/backend context, there shouldn't be a difference vs just using the `ws` package directly.

Was this thought to cut out the middle-man, since you were just using `ws` anyway, or were you looking to use a library other than the [ws](https://github.com/websockets/ws) package?

If that was the motivation, could you tell me more about what implementation you were hoping to do? Would love to understand more about your goal here.

**Comment by tiagosiebler** [comment]
Interesting & yes, I do absolutely love the idea. The biggest question here is the abstraction layer that would accommodate supporting these alternatives, perhaps starting by a baseline of ws implementations to initially support (e.g. `ws`, , socket.io, `µWebSockets`, etc) and looking where/how to support a common ground. Given your questions, have you spent some time with these alternative ws implementations? Perhaps you have some ideas on ways to approach this?

I've also wondered about the following, though the latter points are likely out of scope of this discussion unless you're feeling inspired:
- supporting these in a way that does not require every installation of my SDKs to also install every supported ws implementation, e.g. optional dependencies or some other form of abstraction that gives my SDKs 0 knowledge of these libraries
- supporting an under-the-hood mechanism for handling back-pressure (e.g. a choice whether or not not-yet-handled events should expire or be queued until they're handled). This is particularly important on binance, where connections with back-pressure are forcefully killed by the exchange.
- standardising/abstracting the ws client logic that's the same between all my SDKs, making the per-exchange logic simpler

You're right about replicating across my other SDKs, though standardising/abstracting the repetition would make that easier in the future. Food for thought, I hope!
